apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
  # - apiGroups:
  #     - apiextensions.k8s.io
  #   resources:
  #     - customresourcedefinitions/status
  #   verbs:
  #     - get
  #     - list
  #     - watch
  # - apiGroups:
  #     - coordination.k8s.io
  #   resources:
  #     - leases
  #   verbs:
  #     - create
  #     - delete
  #     - get
  #     - list
  #     - update
  #     - watch
  # - apiGroups:
  #     - ""
  #   resources:
  #     - events
  #   verbs:
  #     - create
  #     - list
  #     - patch
  #     - update
  #     - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  # - apiGroups:
  #     - ""
  #   resources:
  #     - persistentvolumeclaims
  #   verbs:
  #     - create
  #     - delete
  #     - get
  #     - list
  #     - patch
  #     - update
  #     - watch
  # - apiGroups:
  #     - ""
  #   resources:
  #     - persistentvolumeclaims/status
  #   verbs:
  #     - get
  #     - patch
  #     - update
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # - apiGroups:
  #     - ""
  #   resources:
  #     - pods
  #   verbs:
  #     - get
  #     - list
  #     - watch
  # - apiGroups:
  #     - ""
  #   resources:
  #     - secrets
  #   verbs:
  #     - get
  #     - list
  #     - watch
  # - apiGroups:
  #     - replication.storage.dell.com
  #   resources:
  #     - dellcsireplicationgroups
  #   verbs:
  #     - create
  #     - delete
  #     - get
  #     - list
  #     - patch
  #     - update
  #     - watch
  # - apiGroups:
  #     - replication.storage.dell.com
  #   resources:
  #     - dellcsireplicationgroups/status
  #   verbs:
  #     - get
  #     - patch
  #     - update
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
---
# Role for Driver-specific Permissions in a Namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manager-role
  namespace: dell-replication-controller
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - replication.storage.dell.com
    resources:
      - dellcsireplicationgroups
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - replication.storage.dell.com
    resources:
      - dellcsireplicationgroups/status
    verbs:
      - get
      - patch
      - update