general:
  vulnerabilities:
    - CVE-2019-1010022 # "Will not fix", see https://access.redhat.com/security/cve/CVE-2019-1010022
    - CVE-2019-5827    # "Will not fix", see https://access.redhat.com/security/cve/cve-2019-5827
    - CVE-2022-27664   # "Will not fix", see https://access.redhat.com/security/cve/cve-2022-27664
