general:
  vulnerabilities:
    - CVE-2019-1010022 # "Will not fix", see https://access.redhat.com/security/cve/CVE-2019-1010022
    - CVE-2023-0286 # "Will fix", container base image is currently out-of-date.
