apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  {{- if eq .TargetClusterID .SourceClusterID }}
  name: {{ .Name }}-tgt
  {{- else }}
  name: {{ .Name }}
  {{- end }}
provisioner: csi-{{ .Driver }}.dellemc.com
reclaimPolicy: {{ .ReclaimPolicy }}
volumeBindingMode: Immediate
parameters:
  {{ .ReplicationPrefix }}/isReplicationEnabled: "true"
  {{ .ReplicationPrefix }}/remoteStorageClassName: {{ .Name }}
  {{- if eq .TargetClusterID .SourceClusterID }}
  {{ .ReplicationPrefix }}/remoteClusterID: self
  {{- else }}
  {{ .ReplicationPrefix }}/remoteClusterID: {{ .SourceClusterID }}
  {{- end }}
  {{ .ReplicationPrefix }}/rpo: {{ .Parameters.Rpo }}
  {{ .ReplicationPrefix }}/ignoreNamespaces: "{{ .Parameters.IgnoreNamespaces }}"
  {{ .ReplicationPrefix }}/volumeGroupPrefix: {{ .Parameters.VolumeGroupPrefix }}
  {{ .ReplicationPrefix }}/remoteSystem: {{ .Parameters.ClusterName.Source }}
  {{ .ReplicationPrefix }}/remoteRGRetentionPolicy: {{ .RemoteRetentionPolicy.RG }}
  {{ .ReplicationPrefix }}/remotePVRetentionPolicy: {{ .RemoteRetentionPolicy.PV }}
  {{ .ReplicationPrefix }}/remoteAccessZone: {{ .Parameters.AccessZone.Source }}
  {{- if .Parameters.AzServiceIP }}
  {{ .ReplicationPrefix }}/remoteAzServiceIP: {{ .Parameters.AzServiceIP.Source }}
  {{- end }}
  {{ .ReplicationPrefix }}/remoteRootClientEnabled: {{ .Parameters.RootClientEnabled.Source }}
  AccessZone: {{ .Parameters.AccessZone.Target }}
  {{- if .Parameters.AzServiceIP }}
  AzServiceIP: {{ .Parameters.AzServiceIP.Target }}
  {{- end }}
  IsiPath: {{ .Parameters.IsiPath}}
  RootClientEnabled: "{{ .Parameters.RootClientEnabled.Target }}"
  ClusterName: {{ .Parameters.ClusterName.Target }}
