# yamllint disable-file
# This file is not valid YAML because it is a Helm template
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Name }}
provisioner: csi-{{ .Driver }}.dellemc.com
reclaimPolicy: {{ .ReclaimPolicy }}
volumeBindingMode: Immediate
parameters:
  {{ .ReplicationPrefix }}/isReplicationEnabled: "true"
  {{- if eq .TargetClusterID .SourceClusterID }}
  {{ .ReplicationPrefix }}/remoteStorageClassName: {{ .Name }}-tgt
  {{ .ReplicationPrefix }}/remoteClusterID: self
  {{- else }}
  {{ .ReplicationPrefix }}/remoteStorageClassName: {{ .Name }}
  {{ .ReplicationPrefix }}/remoteClusterID: {{ .TargetClusterID }}
  {{- end }}
  {{ .ReplicationPrefix }}/remoteSystem: {{ .Parameters.RemoteSystem.Source }}
  {{ .ReplicationPrefix }}/rpo: {{ .Parameters.Rpo }}
  {{ .ReplicationPrefix }}/mode: {{ .Parameters.Mode }}
  {{ .ReplicationPrefix }}/ignoreNamespaces: "{{ .Parameters.IgnoreNamespaces }}"
  {{ .ReplicationPrefix }}/volumeGroupPrefix: {{ .Parameters.VolumeGroupPrefix }}
  {{ .ReplicationPrefix }}/remoteRGRetentionPolicy: {{ .RemoteRetentionPolicy.RG }}
  {{ .ReplicationPrefix }}/remotePVRetentionPolicy: {{ .RemoteRetentionPolicy.PV }}
  arrayID: {{ .Parameters.ArrayID.Source }}
  {{- if ne .Parameters.SharedNfs "" }}
  shared-nfs: {{ .Parameters.SharedNfs }}
  {{- end }}
