# Copyright © 2020-2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# yamllint disable-file
# This file is not valid YAML because it is a Helm template
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Name }}
provisioner: csi-{{ .Driver }}.dellemc.com
reclaimPolicy: {{ .ReclaimPolicy }}
volumeBindingMode: Immediate
parameters:
  {{ .ReplicationPrefix }}/isReplicationEnabled: "true"
  {{- if eq .TargetClusterID .SourceClusterID }}
  {{ .ReplicationPrefix }}/remoteStorageClassName: {{ .Name }}-tgt
  {{ .ReplicationPrefix }}/remoteClusterID: self
  {{- else }}
  {{ .ReplicationPrefix }}/remoteStorageClassName: {{ .Name }}
  {{ .ReplicationPrefix }}/remoteClusterID: {{ .TargetClusterID }}
  {{- end }}
  SRP: {{ .Parameters.Srp.Source }}
  SYMID: "{{ .Parameters.SymID.Source }}"
  ServiceLevel: "{{ .Parameters.ServiceLevel.Source }}"
  {{ .ReplicationPrefix }}/RdfMode: "{{ .Parameters.RdfMode }}"
  {{ .ReplicationPrefix }}/RemoteSRP: "{{ .Parameters.Srp.Target }}"
  {{ .ReplicationPrefix }}/RemoteSYMID: "{{ .Parameters.SymID.Target }}"
  {{ .ReplicationPrefix }}/RemoteServiceLevel: "{{ .Parameters.ServiceLevel.Target }}"
  {{ .ReplicationPrefix }}/RdfGroup: "{{ .Parameters.RdfGroup.Source }}"
  {{ .ReplicationPrefix }}/RemoteRDFGroup: "{{ .Parameters.RdfGroup.Target }}"
  {{ .ReplicationPrefix }}/remoteRGRetentionPolicy: {{ .RemoteRetentionPolicy.RG }}
  {{ .ReplicationPrefix }}/remotePVRetentionPolicy: {{ .RemoteRetentionPolicy.PV }}