apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Name }}
provisioner: csi-{{ .Driver }}.dellemc.com
reclaimPolicy: {{ .ReclaimPolicy }}
volumeBindingMode: Immediate
parameters:
  {{ .ReplicationPrefix }}/isReplicationEnabled: "true"
  {{- if eq .TargetClusterID .SourceClusterID }}
  {{ .ReplicationPrefix }}/remoteStorageClassName: {{ .Name }}-tgt
  {{ .ReplicationPrefix }}/remoteClusterID: self
  {{- else }}
  {{ .ReplicationPrefix }}/remoteStorageClassName: {{ .Name }}
  {{ .ReplicationPrefix }}/remoteClusterID: {{ .TargetClusterID }}
  {{- end }}
  SRP: {{ .Parameters.Srp.Source }}
  SYMID: "{{ .Parameters.SymId.Source }}"
  ServiceLevel: "{{ .Parameters.ServiceLevel.Source }}"
  {{ .ReplicationPrefix }}/RdfMode: "{{ .Parameters.RdfMode }}"
  {{ .ReplicationPrefix }}/RemoteSRP: "{{ .Parameters.Srp.Target }}"
  {{ .ReplicationPrefix }}/RemoteSYMID: "{{ .Parameters.SymId.Target }}"
  {{ .ReplicationPrefix }}/RemoteServiceLevel: "{{ .Parameters.ServiceLevel.Target }}"
  {{ .ReplicationPrefix }}/RdfGroup: "{{ .Parameters.RdfGroup.Source }}"
  {{ .ReplicationPrefix }}/RemoteRDFGroup: "{{ .Parameters.RdfGroup.Target }}"

