apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Name }}
provisioner: csi-{{ .Driver }}.dellemc.com
reclaimPolicy: {{ .ReclaimPolicy }}
volumeBindingMode: Immediate
parameters:
  {{ .ReplicationPrefix }}/isReplicationEnabled: "true"
  {{- if eq .TargetClusterID .SourceClusterID }}
  {{ .ReplicationPrefix }}/remoteStorageClassName: {{ .Name }}-tgt
  {{ .ReplicationPrefix }}/remoteClusterID: self
  {{- else }}
  {{ .ReplicationPrefix }}/remoteStorageClassName: {{ .Name }}
  {{ .ReplicationPrefix }}/remoteClusterID: {{ .TargetClusterID }}
  {{- end }}
  {{ .ReplicationPrefix }}/rpo: "{{ .Parameters.Rpo }}"
  {{ .ReplicationPrefix }}/ignoreNamespaces: "{{ .Parameters.IgnoreNamespaces }}"
  {{ .ReplicationPrefix }}/volumeGroupPrefix: {{ .Parameters.VolumeGroupPrefix }}
  {{ .ReplicationPrefix }}/remoteRGRetentionPolicy: {{ .RemoteRetentionPolicy.RG }}
  {{ .ReplicationPrefix }}/remotePVRetentionPolicy: {{ .RemoteRetentionPolicy.PV }}
  {{ .ReplicationPrefix }}/remoteSystem: {{ .Parameters.ArrayID.Target }}
  {{ .ReplicationPrefix }}/remoteStoragePool: "{{ .Parameters.StoragePool.Target }}"
  {{ .ReplicationPrefix }}/remoteNasServer: "{{ .Parameters.NasServer.Target }}"
  arrayId: {{ .Parameters.ArrayID.Source }}
  protocol: {{ .Parameters.Protocol }}
  storagePool: {{ .Parameters.StoragePool.Source }}
  nasServer: {{ .Parameters.NasServer.Source }}
