apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Name }}
provisioner: csi-{{ .Driver }}.dellemc.com
reclaimPolicy: {{ .ReclaimPolicy }}
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  storagepool: {{ .Parameters.StoragePool.Source }}
  systemID: {{ .Parameters.ArrayID.Source }}
  protectiondomain: {{ .Parameters.ProtectionDomain.Source }}
  {{ .ReplicationPrefix }}/isReplicationEnabled: "true"
  {{- if eq .TargetClusterID .SourceClusterID }}
  {{ .ReplicationPrefix }}/remoteStorageClassName: {{ .Name }}-tgt
  {{ .ReplicationPrefix }}/remoteClusterID: self
  {{- else }}
  {{ .ReplicationPrefix }}/remoteStorageClassName: {{ .Name }}
  {{ .ReplicationPrefix }}/remoteClusterID: {{ .TargetClusterID }}
  {{- end }}
  {{ .ReplicationPrefix }}/remoteSystem: {{ .Parameters.ArrayID.Target }}
  {{ .ReplicationPrefix }}/remoteStoragePool: {{ .Parameters.StoragePool.Target }}
  {{ .ReplicationPrefix }}/rpo: "{{ .Parameters.Rpo }}"
  {{ .ReplicationPrefix }}/volumeGroupPrefix: {{ .Parameters.VolumeGroupPrefix }}
  {{ .ReplicationPrefix }}/remoteRGRetentionPolicy: {{ .RemoteRetentionPolicy.RG }}
  {{ .ReplicationPrefix }}/remotePVRetentionPolicy: {{ .RemoteRetentionPolicy.PV }}
  {{ .ReplicationPrefix }}/consistencyGroupName: {{ .Parameters.ConsistencyGroupName }}
  {{ .ReplicationPrefix }}/protectionDomain: {{ .Parameters.ProtectionDomain.Target }}
allowedTopologies:
- matchLabelExpressions:
  - key: csi-{{ .Driver }}.dellemc.com/{{ .Parameters.RemoteSystem.Source }}
    values:
    - csi-{{ .Driver }}.dellemc.com