//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DellCSIMigrationGroup) DeepCopyInto(out *DellCSIMigrationGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DellCSIMigrationGroup.
func (in *DellCSIMigrationGroup) DeepCopy() *DellCSIMigrationGroup {
	if in == nil {
		return nil
	}
	out := new(DellCSIMigrationGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DellCSIMigrationGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DellCSIMigrationGroupList) DeepCopyInto(out *DellCSIMigrationGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DellCSIMigrationGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DellCSIMigrationGroupList.
func (in *DellCSIMigrationGroupList) DeepCopy() *DellCSIMigrationGroupList {
	if in == nil {
		return nil
	}
	out := new(DellCSIMigrationGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DellCSIMigrationGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DellCSIMigrationGroupSpec) DeepCopyInto(out *DellCSIMigrationGroupSpec) {
	*out = *in
	if in.MigrationGroupAttributes != nil {
		in, out := &in.MigrationGroupAttributes, &out.MigrationGroupAttributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DellCSIMigrationGroupSpec.
func (in *DellCSIMigrationGroupSpec) DeepCopy() *DellCSIMigrationGroupSpec {
	if in == nil {
		return nil
	}
	out := new(DellCSIMigrationGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DellCSIMigrationGroupStatus) DeepCopyInto(out *DellCSIMigrationGroupStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DellCSIMigrationGroupStatus.
func (in *DellCSIMigrationGroupStatus) DeepCopy() *DellCSIMigrationGroupStatus {
	if in == nil {
		return nil
	}
	out := new(DellCSIMigrationGroupStatus)
	in.DeepCopyInto(out)
	return out
}
