# Init container

# some arguments that must be supplied
ARG BASEIMAGE

FROM golang:1.20 AS builder
WORKDIR /build
RUN wget https://dl.k8s.io/release/v1.26.4/bin/linux/amd64/kubectl -O kubectl

FROM $BASEIMAGE AS init
WORKDIR /upgrade
COPY scripts/upgrade ./
COPY --from=builder /build/kubectl /usr/local/bin/kubectl
RUN chmod +x /upgrade/migrate_rg.sh && \
    chmod +x /usr/local/bin/kubectl
USER 1001
ENTRYPOINT ["/upgrade/migrate_rg.sh"]