FROM scratch AS container-base

# Controller
FROM container-base AS controller
WORKDIR /
COPY bin/dell-replication-controller ./
ENTRYPOINT ["/dell-replication-controller"]

# Sidecar
FROM container-base AS sidecar
WORKDIR /
COPY bin/dell-csi-replicator ./
ENTRYPOINT ["/dell-csi-replicator"]

# Sidecar
FROM container-base AS migrator
WORKDIR /
COPY bin/dell-csi-migrator ./
ENTRYPOINT ["/dell-csi-migrator"]

# Sidecar
FROM container-base AS node-rescaner
WORKDIR /
COPY bin/dell-csi-node-rescaner ./
ENTRYPOINT ["/dell-csi-node-rescaner"]