# some arguments that must be supplied
ARG BASEIMAGE

FROM $BASEIMAGE AS container-base

# Controller
FROM container-base AS controller
WORKDIR /
COPY bin/dell-replication-controller ./
ENTRYPOINT ["/dell-replication-controller"]

# Sidecar
FROM container-base AS sidecar
WORKDIR /
COPY bin/dell-csi-replicator ./
ENTRYPOINT ["/dell-csi-replicator"]

# Sidecar
FROM container-base AS migrator
WORKDIR /
COPY bin/dell-csi-migrator ./
ENTRYPOINT ["/dell-csi-migrator"]

# Sidecar
FROM container-base AS node-rescanner
WORKDIR /
COPY bin/dell-csi-node-rescanner ./
ENTRYPOINT ["/dell-csi-node-rescanner"]