# Init container

# some arguments that must be supplied
ARG BASEIMAGE

FROM amaas-eos-mw1.cec.lab.emc.com:5106/dcm/go-builder-image:latest as builder
WORKDIR /upgrade
COPY scripts/upgrade ./
RUN wget https://dl.k8s.io/release/v1.26.4/bin/linux/amd64/kubectl -O kubectl


FROM $BASEIMAGE AS init
WORKDIR /upgrade
RUN chmod +x /upgrade/migrate_rg.sh
USER 1001    
ENTRYPOINT ["/upgrade/migrate_rg.sh"]