/*
 *
 * Copyright © 2021-2024 Dell Inc. or its subsidiaries. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	k8s "github.com/dell/repctl/pkg/k8s"
	mock "github.com/stretchr/testify/mock"
)

// MultiClusterConfiguratorInterface is an autogenerated mock type for the MultiClusterConfiguratorInterface type
type MultiClusterConfiguratorInterface struct {
	mock.Mock
}

// GetAllClusters provides a mock function with given fields: _a0, _a1
func (_m *MultiClusterConfiguratorInterface) GetAllClusters(_a0 []string, _a1 string) (*k8s.Clusters, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *k8s.Clusters
	if rf, ok := ret.Get(0).(func([]string, string) *k8s.Clusters); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*k8s.Clusters)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
