// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	k8s "github.com/dell/csm-replication/repctl/pkg/k8s"
	mock "github.com/stretchr/testify/mock"
)

// MultiClusterConfiguratorInterface is an autogenerated mock type for the MultiClusterConfiguratorInterface type
type MultiClusterConfiguratorInterface struct {
	mock.Mock
}

// GetAllClusters provides a mock function with given fields: _a0, _a1
func (_m *MultiClusterConfiguratorInterface) GetAllClusters(_a0 []string, _a1 string) (*k8s.Clusters, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetAllClusters")
	}

	var r0 *k8s.Clusters
	var r1 error
	if rf, ok := ret.Get(0).(func([]string, string) (*k8s.Clusters, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func([]string, string) *k8s.Clusters); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*k8s.Clusters)
		}
	}

	if rf, ok := ret.Get(1).(func([]string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMultiClusterConfiguratorInterface creates a new instance of MultiClusterConfiguratorInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMultiClusterConfiguratorInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MultiClusterConfiguratorInterface {
	mock := &MultiClusterConfiguratorInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
