# Copyright © 2020-2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

sourceClusterID: "cluster-k211"
targetClusterID: "cluster-k212"
name: "vxflexos-replication"
driver: "vxflexos"
reclaimPolicy: "Delete"
replicationPrefix: "replication.storage.dell.com"
remoteRetentionPolicy:
  RG: "Delete"
  PV: "Retain"
parameters:
  storagePool:    # populate with storage pool to use of arrays
    source: "pool1"
    target: "pool1"
  protectionDomain:    # populate with protection domain to use of arrays
    source: "domain1"
    target: "domain1"
  arrayID:    # populate with unique ids of storage arrays
    source: "0000000000000001"
    target: "0000000000000002"
  rpo: "60"
  volumeGroupPrefix: "csi"
  consistencyGroupName: ""    # optional name to be given to the rcg
