sourceClusterID: "cluster-1"
targetClusterID: "cluster-2"
name: "powerstore-replication"
driver: "powerstore"
reclaimPolicy: "Delete"
replicationPrefix: "replication.storage.dell.com"
parameters:
  arrayID: # populate with unique ids of storage arrays
    source: "PS8eddd4fad1fc"
    target: "PS2f2494648c52"
  remoteSystem: # populate with name of the remote system as seen from the current PowerStore instance
    source: "RT-D1006"
    target: "RT-D1005"
  rpo: "Five_Minutes"
  ignoreNamespaces: "false"
  volumeGroupPrefix: "csi"
