# replicas: Defines number of controller replicas
# Allowed values: int
# Default value: 1
replicas: 1

# image: Defines controller image. This shouldn't be changed
# Allowed values: string
image: dellemc/dell-replication-controller:v1.0.0

# logLevel: Defines initial log level for controller. This can be changed in runtime
# Allowed values: "debug", "info", "warn", "error", "panic"
# Default value: "info"
logLevel: "info"

# leaderElection: Enable leader election for dell-replication-controller manager.
# Enabling this will ensure there is only one active dell-replication-controller manager.
# Allowed values: "true", "false"
# Default value: "true"
leaderElection: "true"

# retryIntervalMin: Initial retry interval of failed reconcile request.
# It doubles with each failure, upto retry-interval-max
# Allowed values: int (seconds)
retryIntervalMin: 1

# retryIntervalMax: Maximum retry interval of failed reconcile request
# Allowed values: int (seconds)
retryIntervalMax: 5