name: Workflow
on:    # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  sanitize:
    name: Check for forbidden words
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Run the forbidden words scan
        uses: dell/common-github-actions/code-sanitizer@main
        with:
          args: /github/workspace
  go_security_scan_repctl:
    permissions: write-all
    name: Go security - Repctl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Run gosec
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/securego/gosec/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')

          cd ./repctl
          wget https://github.com/securego/gosec/releases/download/$(LATEST_VERSION)/gosec_$(LATEST_VERSION)_linux_amd64.tar.gz
          tar xzf gosec_$(LATEST_VERSION)_linux_amd64.tar.gz
          ./gosec  ./...
